In [1]:
import json
import re
import pandas as pd
from typing import Dict
import html 
bacteria_regex = r'(?P<bacterium>[A-Z]\. [a-z]+)(?P<strain>\s?[A-Z]+\s?[0-9]+)?'

In [2]:
df = pd.read_csv('APD6_processed.csv',dtype={"APD_ID":str})
print(f"初始数据集中存在的行总共有{len(df)}\n")
df["APD_ID"] = "AP" + df["APD_ID"]
# 氨基酸序列要清洗，保留20种标准的氨基酸字母
def clean_sequence(seq: str) -> str:
    seq = seq.upper().strip()
    standard_aa = set("ACDEFGHIKLMNPQRSTVWY")
    if set(seq).issubset(standard_aa):
        return seq
    else:
        return None
df["Sequence"] = df["Sequence"].apply(clean_sequence)
df = df.dropna(subset=['Sequence'])
print(f"氨基酸序列清洗后存在的行总共有{len(df)}\n")
df.head(5)

/tmp/ipykernel_2783122/2703227181.py:1: DtypeWarning: Columns (4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,128,129,130,131,132,133,134,135,136,137,138,139,140,141,142,143,144,145,146,147,148,149,150,151,152,153,154,155,156,157,158,159,160,161,162,163,164,165,166,167,168,169,170,172,173,174,175,176,177,178,179,180,181,182,183,184,185,186,187,188,189,190,191,192,193,194,195,196,197,198,199,200,201,202,203,204,205,206,207,208,209,210,211,212,213,214,215,216,217,218,219,220,221,222,223,224,225,226,227,228,229,230,231,232,233,234,235,236,237,238,239,240,241,242,243,244,245,246,247,248,249,250,251,252,253,254,255,256,257,258,259,260,261,262,263,264,265,266,267,268,269,270,271,272,273,274,275,276,277,278,279,280,281,282,283,284,285,286,287,288,289,290,291,292,293,294,295,296,297,299,300,301,302,303,304,305,306,307,308,309,310,311,312,313,314,315,316,317,318,319,320,321,322,323,325,326,327,328,329,330,331,332,333,334,335,336,337,338,339,340,341,342,343,344,345,346,347,348,349,350,351,352,353,354,355,356,357,358,359,360,361,362,363,364,365,366,367,368,369,370,371,372,373,375,376,377,378,379,380,381,382,383,384,385,386,387,388,389,390,391,392,393,394,395,396,397,398,399,400,401,402,403,404,405,406,407,408,409,410,411,412,413,414,415,416,417,418,419,420,421,422,423,424,425,426,427,428,429,430,431,432,433,434,435,436,437,438,439,440,441,442,443,444,445,446,447,448,449,450,451,452,453,454,455,456,457,458,459,460,461,462,463,464,465,466,467,468,469,470,471,472,473,474,475,476,477,478,479,480,481,482,483,484,485,486,487,488,489,490,491,492,493,494,495,496,497,498,499,500,501,502,503,504,505,506,507,508,509,510,511,512,513,514,515,516,517,518,519,520,521,522,523,524,525,526,527,528,529,530,531,532,533,534,535,536,537,538,539,540,541,542,543,544,545,546,547,548,549,550,551,552,553,554,555,556,557,558,559,560,561,562,563,564,565,566,567,568,569,570,571,572,573,574,575,576,577,578,579,580,581,582,583,584,585,586,587,588,589,590,591,592,593,594,596,597,598,599,600,601,602,603,604,605,606,607,608,609,610,611,612,613,614,615,616,617,618,619,620,621,622,623,624,625,626,627,628,629,630,631,632,633,634,635,636,637,638,639,640,641,642,643,644,645,646,647,648,649,650,651,652,653,654,655,656,657,658,659,660,661,662,663,664,665,666,667,668,669,670,671,672,673,674,675,676,677,678,679,680,681,682,683,684,685,686,687,688,689,690,691,692,693,694,695,696,697,698,699,700,701,702,703,704,705,706,707,708,709,710,711,712,713,715,716,717,718,719,720,721,722,723,724,725,726,727,728,729,730,731,732,733,734,735,736,737,738,739,740,741,742,743,744,745,746,747,748,749,750,751,752,753,754,755,756,757,758,759,760,761,762,763,764,765,766,767,768,769,770,771,772,773,774,775,776,777,778,779,780,781,782,783,784,785,786,787,789,790,791,792,793,794,795,796,797,798,799,800,801,802,803,804,805,806,807,808,809,810,811,812,813,814,815,816,817,818,819,820,821,822,823,824,825,826,827,828,829,830,831,832,833,834,835,836,837,838,839,840,841,842,843,844,845,846,847,848,849,850,851,852,853,854,855,856,857,858,859,860,861,862,863,864,865,866,867,868,869,870,871,872,873,874,875,876,877,878,879,880,881,882,883,884,885,886,887,888,889,890,891,892,893,894,895,896,897,898,899,900,901,902,903,904,905,906,907,908,909,910,911,912,913,914,915,916,917,918,919,920,921,922,923,924,925,926,927,928,929,930,931,932,933,934,935,937,938,939,940,941,942,943,944,945,946,947,948,949,950,951,952,953,954,955,956,957,958,959,960,961,962,963,964,965,966,967,968,969,970,971,972,973,974,975,976,977,978,979,980,981,982,983,984,985,986,987,988,989,990,991,992,993,994,995,996,997,998,999,1000,1001,1002,1003,1004,1005,1006,1007,1008,1009,1010,1011,1012,1013,1014,1015,1016,1017,1018,1019,1020,1021,1022,1023,1024,1025,1026,1027,1028,1029,1030,1031,1032,1033,1034,1035,1036,1037,1038,1039,1040,1041,1042,1044,1045,1046,1047,1048,1049,1050,1051,1052,1053,1054,1055,1056,1057,1058,1059,1060,1061,1062,1063,1064,1065,1066,1067,1068,1069,1070,1071,1072,1073,1074,1075,1076,1077,1078,1079,1080,1081,1082,1083,1084,1085,1086,1087,1088,1089,1090,1091,1092,1093,1094,1095,1096,1097,1098,1099,1100,1101,1102,1103,1104,1105,1106,1107,1108,1109,1110,1111,1112,1113,1114,1115,1116,1117,1118,1119,1120,1121,1123,1124,1125,1126,1127,1128,1129,1130,1131,1132,1133,1134,1135,1136,1137,1138,1139,1140,1141,1142,1143,1144,1145,1146,1147,1148,1149,1150,1151,1152,1153,1154,1155,1156,1157,1158,1159,1160,1161,1162,1163,1164,1165,1166,1167,1168,1169,1170,1171,1172,1173,1174,1175,1176,1177,1178,1179,1180,1181,1182,1183,1184,1185,1186,1187,1188,1189,1190,1192,1193,1194,1195,1196,1197,1198,1199,1200,1201,1202,1203,1204,1205,1206,1207,1208,1209,1210,1211,1212,1213,1214,1215,1216,1217,1218,1219,1220,1221,1222,1223,1224,1225,1226,1227,1228,1229,1230,1231,1232,1233,1234,1235,1236,1237,1238,1239,1240,1241,1242,1243,1244,1245,1246,1247,1248,1250,1251,1252,1253,1254,1255,1256,1257,1258,1259,1260,1261,1262,1263,1264,1265,1266,1267,1268,1269,1270,1271,1272,1273,1274,1275,1276,1277,1278,1279,1280,1281,1282,1283,1284,1285,1286,1287,1288,1289,1290,1291,1292,1293,1294,1295,1296,1297,1298,1299,1300,1301,1302,1303,1304,1305,1306,1307,1308,1309,1310,1311,1312,1313,1314,1315,1316,1317,1318,1319,1320,1321,1322,1323,1324,1325,1326,1327,1328,1329,1330,1331,1332,1333,1334,1335,1336,1337,1338,1339,1340,1341,1342,1343,1344,1345,1346,1347,1348,1349,1350,1351,1352,1353,1354,1355,1356,1357,1358,1359,1360,1361,1362,1363,1364,1365,1366,1367,1368,1369,1370,1371,1372,1373,1374,1375,1376,1377,1378,1379,1380,1381,1382,1383,1384,1385,1386,1387,1388,1389,1390,1391,1392,1393,1394,1395,1396,1397,1398,1399,1400,1401,1402,1403,1404,1405,1406,1407,1409,1410,1411,1412,1413,1414,1415,1416,1417,1419,1420,1421,1422,1423,1424,1425,1426,1427,1428,1429,1430,1431,1432,1433,1434,1435,1436,1437,1438,1439,1440,1441,1442,1443,1444,1445,1446,1447,1448,1449,1450,1451,1452,1453,1454,1455,1456,1457,1458,1459,1460,1461,1462,1463,1464,1465,1466,1467,1468,1469,1470,1471,1472,1473,1474,1475,1476,1477,1478,1479,1480,1481,1482,1483,1484,1485,1486,1487,1488,1489,1490,1491,1492,1493,1494,1495,1496,1497,1498,1499,1500,1501,1502,1503,1504,1505,1506,1507,1508,1509,1510,1511,1512,1514,1515,1516,1517,1518,1519,1520,1521,1522,1523,1524,1525,1526,1527,1528,1529,1530,1531,1532,1533,1534,1535,1536,1537,1538,1539,1540,1541,1542,1543,1544,1545,1546,1547,1548,1549,1550,1551,1552,1553,1554,1555,1556,1557,1558,1559,1560,1561,1562,1563,1564,1565,1566,1567,1568,1569,1570,1571,1572,1573,1574,1575,1577,1578,1579,1580,1581,1582,1583,1584,1585,1586,1587,1588,1589,1590,1591,1592,1593,1594,1595,1596,1597,1598,1599,1600,1601,1602,1603,1604,1605,1606,1607,1608,1609,1610,1611,1612,1613,1614,1615,1616,1617,1618,1620,1621,1622,1623,1624,1625,1626,1627,1628,1629,1630,1631,1632,1633,1634,1635,1636,1637,1638,1639,1640,1641,1642,1643,1644,1645,1646,1647,1648,1649,1650,1651,1652,1653,1654,1655,1656,1657,1658,1659,1660,1661,1662,1663,1664,1665,1666,1667,1668,1669,1670,1671,1672,1673,1674,1675,1676,1677,1678,1679,1680,1681,1682,1683,1684,1685,1686,1687,1688,1689,1690,1691,1692,1693,1694,1695,1696,1697,1698,1699,1700,1701,1702,1703,1704,1705,1706,1707,1708,1709,1710,1711,1712,1713,1714,1715,1716,1717,1718,1719,1720,1721,1722,1723,1724,1725,1726,1727,1728,1729,1730,1731,1732,1733,1734,1735,1736,1737,1738,1739,1740,1741,1742,1743,1744,1745,1746,1747,1748,1749,1750,1751,1752,1753,1754,1755,1756,1757,1758,1759,1760,1761,1762,1763,1764,1765,1766,1767,1768,1769,1770,1771,1772,1773,1774,1775,1776,1777,1778,1779,1780,1781,1782,1783,1784,1785,1786,1787,1788,1789,1790,1791,1792,1793,1794,1795,1796,1797,1798,1799,1800,1801,1802,1803,1804,1805,1806,1807,1808,1809,1810,1811,1812,1813,1814,1815,1816,1817,1818,1819,1820,1821,1822,1823,1824,1825,1826,1827,1828,1829,1830,1831,1832,1833,1834,1835,1836,1837,1838,1839,1841,1842,1843,1844,1845,1846,1847,1848,1849,1850,1851,1852,1853,1854,1855,1856,1857,1858,1859,1860,1861,1862,1863,1864,1865,1866,1867,1868,1869,1870,1871,1872,1873,1874,1875,1876,1877,1878,1879,1880,1881,1882,1883,1884,1885,1886,1887,1888,1889,1890,1891,1892,1893,1894,1895,1896,1897,1898,1899,1900,1901,1902,1903,1904,1905,1906,1907,1908,1909,1910,1911,1912,1913,1914,1915,1916,1917,1918,1919,1920,1921,1922,1923,1924,1925,1926,1927,1928,1929,1930,1931,1932,1933,1934,1935,1936,1937,1938,1939,1940,1941,1942,1943,1944,1945,1946,1947,1948,1949,1950,1951,1952,1953,1954,1955,1956,1957,1958,1959,1960,1961,1962,1963,1964,1965,1966,1967,1968,1969,1970,1971,1972,1973,1974,1975,1976,1977,1978,1979,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('APD6_processed.csv',dtype={"APD_ID":str})

初始数据集中存在的行总共有6070

氨基酸序列清洗后存在的行总共有6062

,APD_ID,Sequence,Length,Activity,MIC (A. acidoterrestris ATCC 49025),MIC (A. acidoterrestris),MIC (A. actinomycetemcomitans),MIC (A. alternata),MIC (A. alternatam),MIC (A. aumannii B28),...,HC50 ( female murine RBC),HC50 ( highly hemolytic),HC50 ( horse RBC),HC50 ( human RBC),HC50 ( moderate hemolytic),HC50 ( murine RBC),HC50 ( porcine RBC),HC50 ( rat RBC),HC50 (In vitro Toxicity),HC50 (lytic)
0,AP00004,NLCERASLTWTGNCGNTGHCDTQCRNWESAKHGACHKRGNWKCFCYFDC,49,"Anti-Gram+, Antifungal",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,AP00001,GLWSKIKEVGKEAAKAAAKAAGKAALGAVSEAV,33,"Anti-Gram+ & Gram-, Antifungal, candidacidal, ...",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,AP00002,YVPLPNVPQPGRRPFPTFPGQGPFNPKIKWPQGY,34,Anti-Gram+ & Gram-,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,AP00003,DGVKLCDVPSGTWSGHCGSSSKCSQQCKDREHFAYGGACHYQFPSV...,54,Antifungal,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,AP00006,GNNRPVYIPQPRPPHPRI,18,"Anti-Gram+ & Gram-, anti-sepsis",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
id_vars = ['APD_ID', 'Sequence', 'Length', 'Activity']

# 3. 自动筛选所有以 "HC50" 开头的列作为转换的目标
value_vars = [col for col in df.columns if col.startswith('HC50')]
long_df = df.melt(
    id_vars=id_vars,
    value_vars=value_vars,
    var_name='Raw_Species',
    value_name='HC50_Value'
)
long_df.head(2)

,APD_ID,Sequence,Length,Activity,Raw_Species,HC50_Value
0,AP00004,NLCERASLTWTGNCGNTGHCDTQCRNWESAKHGACHKRGNWKCFCYFDC,49,"Anti-Gram+, Antifungal",HC50 ( Human RBC),NaN
1,AP00001,GLWSKIKEVGKEAAKAAAKAAGKAALGAVSEAV,33,"Anti-Gram+ & Gram-, Antifungal, candidacidal, ...",HC50 ( Human RBC),NaN

In [4]:
long_df.dropna(subset=['HC50_Value'], inplace=True)
print(f"清洗后存在HC50值的行总共有{len(long_df)}\n")
long_df.head(2)

清洗后存在HC50值的行总共有178

,APD_ID,Sequence,Length,Activity,Raw_Species,HC50_Value
344,AP00367,GGLRSLGRKILRAWKKYGPIIVPIIRIG,28,"Anti-Gram+ & Gram-, Antiviral, Antifungal, can...",HC50 ( Human RBC),<100 uM
9152,AP03328,TLKIIVKVVKYLV,13,"Anti-Gram+ & Gram-, Anti-MRSA, Hemolytic",HC50 ( highly hemolytic),=25.1 ug/ml

In [5]:
long_df['Raw_Species'].value_counts()

Raw_Species
HC50 ( porcine RBC)           65
HC50 ( human RBC)             49
HC50 ( Human RBC)             19
HC50 ( murine RBC)            13
HC50 ( rat RBC)               10
HC50 ( horse RBC)              7
HC50 ( Hemolysis)              4
HC50 (  human RBC)             4
HC50 ( female murine RBC)      1
HC50 (  Human RBC)             1
HC50 (  highly hemolytic)      1
HC50 ( highly hemolytic)       1
HC50 ( moderate hemolytic)     1
HC50 (In vitro Toxicity)       1
HC50 (lytic)                   1
Name: count, dtype: int64

In [6]:
long_df['HC50_Value'].value_counts()

HC50_Value
>128 ug/ml     66
>320 uM        13
>250 uM        13
>128 uM         8
>250 ug/ml      8
>500 uM         6
=>128 ug/ml     6
>686 uM         5
>100 uM         4
>256 uM         4
>500 ug/ml      3
>>200 uM        3
>256 ug/ml      3
>265 uM         2
>100 ug/ml      2
=32 uM          2
>>250 ug/ml     2
>200 uM         2
<100 uM         2
=50 uM          1
=6.3 uM         1
=5 0            1
=25 uM          1
=25.1 ug/ml     1
>150 ug/ml      1
>1280 ug/ml     1
=3 2            1
>512 ug/ml      1
>150 uM         1
>300 uM         1
>125 ug/ml      1
>110.6 uM       1
=1 6            1
=18.8 ug/ml     1
<10 ug/ml       1
>381 ug/ml      1
=41.87 uM       1
>600 uM         1
>1000 ug/ml     1
=73.1 ug/ml     1
>122.1 uM       1
>230.6 uM       1
>>50 uM         1
Name: count, dtype: int64

In [8]:

df = pd.read_csv('APD6_processed.csv',dtype={"APD_ID":str})
print(f"初始数据集中存在的行总共有{len(df)}\n")
df["APD_ID"] = "AP" + df["APD_ID"]
# 氨基酸序列要清洗，保留20种标准的氨基酸字母
def clean_sequence(seq: str) -> str:
    seq = seq.upper().strip()
    standard_aa = set("ACDEFGHIKLMNPQRSTVWY")
    if set(seq).issubset(standard_aa):
        return seq
    else:
        return None
df["Sequence"] = df["Sequence"].apply(clean_sequence)
df = df.dropna(subset=['Sequence'])
print(f"氨基酸序列清洗后存在的行总共有{len(df)}\n")
df.head(5)

/tmp/ipykernel_1603596/2566429194.py:1: DtypeWarning: Columns (4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,128,129,130,131,132,133,134,135,136,137,138,139,140,141,142,143,144,145,146,147,148,149,150,151,152,153,154,155,156,157,158,159,160,161,162,163,164,165,166,167,168,169,170,172,173,174,175,176,177,178,179,180,181,182,183,184,185,186,187,188,189,190,191,192,193,194,195,196,197,198,199,200,201,202,203,204,205,206,207,208,209,210,211,212,213,214,215,216,217,218,219,220,221,222,223,224,225,226,227,228,229,230,231,232,233,234,235,236,237,238,239,240,241,242,243,244,245,246,247,248,249,250,251,252,253,254,255,256,257,258,259,260,261,262,263,264,265,266,267,268,269,270,271,272,273,274,275,276,277,278,279,280,281,282,283,284,285,286,287,288,289,290,291,292,293,294,295,296,297,299,300,301,302,303,304,305,306,307,308,309,310,311,312,313,314,315,316,317,318,319,320,321,322,323,325,326,327,328,329,330,331,332,333,334,335,336,337,338,339,340,341,342,343,344,345,346,347,348,349,350,351,352,353,354,355,356,357,358,359,360,361,362,363,364,365,366,367,368,369,370,371,372,373,375,376,377,378,379,380,381,382,383,384,385,386,387,388,389,390,391,392,393,394,395,396,397,398,399,400,401,402,403,404,405,406,407,408,409,410,411,412,413,414,415,416,417,418,419,420,421,422,423,424,425,426,427,428,429,430,431,432,433,434,435,436,437,438,439,440,441,442,443,444,445,446,447,448,449,450,451,452,453,454,455,456,457,458,459,460,461,462,463,464,465,466,467,468,469,470,471,472,473,474,475,476,477,478,479,480,481,482,483,484,485,486,487,488,489,490,491,492,493,494,495,496,497,498,499,500,501,502,503,504,505,506,507,508,509,510,511,512,513,514,515,516,517,518,519,520,521,522,523,524,525,526,527,528,529,530,531,532,533,534,535,536,537,538,539,540,541,542,543,544,545,546,547,548,549,550,551,552,553,554,555,556,557,558,559,560,561,562,563,564,565,566,567,568,569,570,571,572,573,574,575,576,577,578,579,580,581,582,583,584,585,586,587,588,589,590,591,592,593,594,596,597,598,599,600,601,602,603,604,605,606,607,608,609,610,611,612,613,614,615,616,617,618,619,620,621,622,623,624,625,626,627,628,629,630,631,632,633,634,635,636,637,638,639,640,641,642,643,644,645,646,647,648,649,650,651,652,653,654,655,656,657,658,659,660,661,662,663,664,665,666,667,668,669,670,671,672,673,674,675,676,677,678,679,680,681,682,683,684,685,686,687,688,689,690,691,692,693,694,695,696,697,698,699,700,701,702,703,704,705,706,707,708,709,710,711,712,713,715,716,717,718,719,720,721,722,723,724,725,726,727,728,729,730,731,732,733,734,735,736,737,738,739,740,741,742,743,744,745,746,747,748,749,750,751,752,753,754,755,756,757,758,759,760,761,762,763,764,765,766,767,768,769,770,771,772,773,774,775,776,777,778,779,780,781,782,783,784,785,786,787,789,790,791,792,793,794,795,796,797,798,799,800,801,802,803,804,805,806,807,808,809,810,811,812,813,814,815,816,817,818,819,820,821,822,823,824,825,826,827,828,829,830,831,832,833,834,835,836,837,838,839,840,841,842,843,844,845,846,847,848,849,850,851,852,853,854,855,856,857,858,859,860,861,862,863,864,865,866,867,868,869,870,871,872,873,874,875,876,877,878,879,880,881,882,883,884,885,886,887,888,889,890,891,892,893,894,895,896,897,898,899,900,901,902,903,904,905,906,907,908,909,910,911,912,913,914,915,916,917,918,919,920,921,922,923,924,925,926,927,928,929,930,931,932,933,934,935,937,938,939,940,941,942,943,944,945,946,947,948,949,950,951,952,953,954,955,956,957,958,959,960,961,962,963,964,965,966,967,968,969,970,971,972,973,974,975,976,977,978,979,980,981,982,983,984,985,986,987,988,989,990,991,992,993,994,995,996,997,998,999,1000,1001,1002,1003,1004,1005,1006,1007,1008,1009,1010,1011,1012,1013,1014,1015,1016,1017,1018,1019,1020,1021,1022,1023,1024,1025,1026,1027,1028,1029,1030,1031,1032,1033,1034,1035,1036,1037,1038,1039,1040,1041,1042,1044,1045,1046,1047,1048,1049,1050,1051,1052,1053,1054,1055,1056,1057,1058,1059,1060,1061,1062,1063,1064,1065,1066,1067,1068,1069,1070,1071,1072,1073,1074,1075,1076,1077,1078,1079,1080,1081,1082,1083,1084,1085,1086,1087,1088,1089,1090,1091,1092,1093,1094,1095,1096,1097,1098,1099,1100,1101,1102,1103,1104,1105,1106,1107,1108,1109,1110,1111,1112,1113,1114,1115,1116,1117,1118,1119,1120,1121,1123,1124,1125,1126,1127,1128,1129,1130,1131,1132,1133,1134,1135,1136,1137,1138,1139,1140,1141,1142,1143,1144,1145,1146,1147,1148,1149,1150,1151,1152,1153,1154,1155,1156,1157,1158,1159,1160,1161,1162,1163,1164,1165,1166,1167,1168,1169,1170,1171,1172,1173,1174,1175,1176,1177,1178,1179,1180,1181,1182,1183,1184,1185,1186,1187,1188,1189,1190,1192,1193,1194,1195,1196,1197,1198,1199,1200,1201,1202,1203,1204,1205,1206,1207,1208,1209,1210,1211,1212,1213,1214,1215,1216,1217,1218,1219,1220,1221,1222,1223,1224,1225,1226,1227,1228,1229,1230,1231,1232,1233,1234,1235,1236,1237,1238,1239,1240,1241,1242,1243,1244,1245,1246,1247,1248,1250,1251,1252,1253,1254,1255,1256,1257,1258,1259,1260,1261,1262,1263,1264,1265,1266,1267,1268,1269,1270,1271,1272,1273,1274,1275,1276,1277,1278,1279,1280,1281,1282,1283,1284,1285,1286,1287,1288,1289,1290,1291,1292,1293,1294,1295,1296,1297,1298,1299,1300,1301,1302,1303,1304,1305,1306,1307,1308,1309,1310,1311,1312,1313,1314,1315,1316,1317,1318,1319,1320,1321,1322,1323,1324,1325,1326,1327,1328,1329,1330,1331,1332,1333,1334,1335,1336,1337,1338,1339,1340,1341,1342,1343,1344,1345,1346,1347,1348,1349,1350,1351,1352,1353,1354,1355,1356,1357,1358,1359,1360,1361,1362,1363,1364,1365,1366,1367,1368,1369,1370,1371,1372,1373,1374,1375,1376,1377,1378,1379,1380,1381,1382,1383,1384,1385,1386,1387,1388,1389,1390,1391,1392,1393,1394,1395,1396,1397,1398,1399,1400,1401,1402,1403,1404,1405,1406,1407,1409,1410,1411,1412,1413,1414,1415,1416,1417,1419,1420,1421,1422,1423,1424,1425,1426,1427,1428,1429,1430,1431,1432,1433,1434,1435,1436,1437,1438,1439,1440,1441,1442,1443,1444,1445,1446,1447,1448,1449,1450,1451,1452,1453,1454,1455,1456,1457,1458,1459,1460,1461,1462,1463,1464,1465,1466,1467,1468,1469,1470,1471,1472,1473,1474,1475,1476,1477,1478,1479,1480,1481,1482,1483,1484,1485,1486,1487,1488,1489,1490,1491,1492,1493,1494,1495,1496,1497,1498,1499,1500,1501,1502,1503,1504,1505,1506,1507,1508,1509,1510,1511,1512,1514,1515,1516,1517,1518,1519,1520,1521,1522,1523,1524,1525,1526,1527,1528,1529,1530,1531,1532,1533,1534,1535,1536,1537,1538,1539,1540,1541,1542,1543,1544,1545,1546,1547,1548,1549,1550,1551,1552,1553,1554,1555,1556,1557,1558,1559,1560,1561,1562,1563,1564,1565,1566,1567,1568,1569,1570,1571,1572,1573,1574,1575,1577,1578,1579,1580,1581,1582,1583,1584,1585,1586,1587,1588,1589,1590,1591,1592,1593,1594,1595,1596,1597,1598,1599,1600,1601,1602,1603,1604,1605,1606,1607,1608,1609,1610,1611,1612,1613,1614,1615,1616,1617,1618,1620,1621,1622,1623,1624,1625,1626,1627,1628,1629,1630,1631,1632,1633,1634,1635,1636,1637,1638,1639,1640,1641,1642,1643,1644,1645,1646,1647,1648,1649,1650,1651,1652,1653,1654,1655,1656,1657,1658,1659,1660,1661,1662,1663,1664,1665,1666,1667,1668,1669,1670,1671,1672,1673,1674,1675,1676,1677,1678,1679,1680,1681,1682,1683,1684,1685,1686,1687,1688,1689,1690,1691,1692,1693,1694,1695,1696,1697,1698,1699,1700,1701,1702,1703,1704,1705,1706,1707,1708,1709,1710,1711,1712,1713,1714,1715,1716,1717,1718,1719,1720,1721,1722,1723,1724,1725,1726,1727,1728,1729,1730,1731,1732,1733,1734,1735,1736,1737,1738,1739,1740,1741,1742,1743,1744,1745,1746,1747,1748,1749,1750,1751,1752,1753,1754,1755,1756,1757,1758,1759,1760,1761,1762,1763,1764,1765,1766,1767,1768,1769,1770,1771,1772,1773,1774,1775,1776,1777,1778,1779,1780,1781,1782,1783,1784,1785,1786,1787,1788,1789,1790,1791,1792,1793,1794,1795,1796,1797,1798,1799,1800,1801,1802,1803,1804,1805,1806,1807,1808,1809,1810,1811,1812,1813,1814,1815,1816,1817,1818,1819,1820,1821,1822,1823,1824,1825,1826,1827,1828,1829,1830,1831,1832,1833,1834,1835,1836,1837,1838,1839,1841,1842,1843,1844,1845,1846,1847,1848,1849,1850,1851,1852,1853,1854,1855,1856,1857,1858,1859,1860,1861,1862,1863,1864,1865,1866,1867,1868,1869,1870,1871,1872,1873,1874,1875,1876,1877,1878,1879,1880,1881,1882,1883,1884,1885,1886,1887,1888,1889,1890,1891,1892,1893,1894,1895,1896,1897,1898,1899,1900,1901,1902,1903,1904,1905,1906,1907,1908,1909,1910,1911,1912,1913,1914,1915,1916,1917,1918,1919,1920,1921,1922,1923,1924,1925,1926,1927,1928,1929,1930,1931,1932,1933,1934,1935,1936,1937,1938,1939,1940,1941,1942,1943,1944,1945,1946,1947,1948,1949,1950,1951,1952,1953,1954,1955,1956,1957,1958,1959,1960,1961,1962,1963,1964,1965,1966,1967,1968,1969,1970,1971,1972,1973,1974,1975,1976,1977,1978,1979,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('APD6_processed.csv',dtype={"APD_ID":str})

初始数据集中存在的行总共有6070

氨基酸序列清洗后存在的行总共有6062

,APD_ID,Sequence,Length,Activity,MIC (A. acidoterrestris ATCC 49025),MIC (A. acidoterrestris),MIC (A. actinomycetemcomitans),MIC (A. alternata),MIC (A. alternatam),MIC (A. aumannii B28),...,HC50 ( female murine RBC),HC50 ( highly hemolytic),HC50 ( horse RBC),HC50 ( human RBC),HC50 ( moderate hemolytic),HC50 ( murine RBC),HC50 ( porcine RBC),HC50 ( rat RBC),HC50 (In vitro Toxicity),HC50 (lytic)
0,AP00004,NLCERASLTWTGNCGNTGHCDTQCRNWESAKHGACHKRGNWKCFCYFDC,49,"Anti-Gram+, Antifungal",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,AP00001,GLWSKIKEVGKEAAKAAAKAAGKAALGAVSEAV,33,"Anti-Gram+ & Gram-, Antifungal, candidacidal, ...",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,AP00002,YVPLPNVPQPGRRPFPTFPGQGPFNPKIKWPQGY,34,Anti-Gram+ & Gram-,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,AP00003,DGVKLCDVPSGTWSGHCGSSSKCSQQCKDREHFAYGGACHYQFPSV...,54,Antifungal,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,AP00006,GNNRPVYIPQPRPPHPRI,18,"Anti-Gram+ & Gram-, anti-sepsis",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
# 做一个demo csv

id_vars = ['APD_ID', 'Sequence', 'Length', 'Activity']

# 3. 自动筛选所有以 "MIC(E. coli)" 开头的列作为转换的目标
value_vars = [col for col in df.columns if col.startswith('MIC(E. coli')]
demo_df = df.melt(
    id_vars=id_vars,
    value_vars=value_vars,
    var_name='Raw_Species',
    value_name='MIC_Value'
)
demo_df = demo_df.dropna(subset=['MIC_Value'])
print(f"清洗后存在MIC值的行总共有{len(demo_df)}\n")
demo_df.head(2)

In [7]:

id_vars = ['APD_ID', 'Sequence', 'Length', 'Activity']

# 3. 自动筛选所有以 "MIC" 开头的列作为转换的目标
value_vars = [col for col in df.columns if col.startswith('MIC')]
long_df = df.melt(
    id_vars=id_vars,
    value_vars=value_vars,
    var_name='Raw_Species',
    value_name='MIC_Value'
)
long_df.head(2)

,APD_ID,Sequence,Length,Activity,Raw_Species,MIC_Value
0,AP00004,NLCERASLTWTGNCGNTGHCDTQCRNWESAKHGACHKRGNWKCFCYFDC,49,"Anti-Gram+, Antifungal",MIC (A. acidoterrestris ATCC 49025),NaN
1,AP00001,GLWSKIKEVGKEAAKAAAKAAGKAALGAVSEAV,33,"Anti-Gram+ & Gram-, Antifungal, candidacidal, ...",MIC (A. acidoterrestris ATCC 49025),NaN

In [ ]:
long_df["MIC_Value"].describe()

count      16697
unique      1362
top       8  uM)
freq         523
Name: MIC_Value, dtype: object

In [8]:


long_df = long_df.dropna(subset=['MIC_Value'])
print(f"MIC 值存在的行总共有{len(long_df)}\n")

# MIC值变成数值，加上单位，统一处理成μg/mL

from Bio.SeqUtils import molecular_weight
def unify_to_ug_ml(row):
    # mic值是几何平均，没有大于或者小于
    raw_val = str(row['MIC_Value']).lower()
    seq = row['Sequence']
    
    # 1. 提取数值
    match = re.search(r'([\d\.]+)', raw_val)
    if not match: return None
    value = float(match.group(1))

    
    # 2. 如果已经是 ug/ml，直接返回数值
    if 'ug/ml' in raw_val:
        return value
        
    # 3. 如果是 uM，则根据序列计算分子量并转换
    if 'um' in raw_val:
        # 计算分子量 (Da)
        mw = molecular_weight(seq, seq_type="protein")
        print(f"分子质量是{mw} g/mol\n")
        # 转换公式：(uM * MW) / 1000 = ug/ml
        return (value * mw) / 1000
    
    return value # 默认返回
long_df["MIC_Value(ug/ml)"] = long_df.apply(unify_to_ug_ml,axis=1)
long_df = long_df.dropna(subset=['MIC_Value(ug/ml)'])
print(f"MIC 值清洗后存在的行总共有{len(long_df)}\n")
# 16695

MIC 值存在的行总共有16697

分子质量是1044.2255 g/mol

分子质量是2549.041 g/mol

分子质量是4614.266900000001 g/mol

分子质量是2902.3104000000003 g/mol

分子质量是3178.7704000000003 g/mol

分子质量是3164.7438 g/mol

分子质量是3148.7444000000005 g/mol

分子质量是3252.8456 g/mol

分子质量是1516.9088000000002 g/mol

分子质量是1550.9250000000002 g/mol

分子质量是607.4789000000001 g/mol

分子质量是2142.6029999999996 g/mol

分子质量是2176.6191999999996 g/mol

分子质量是2326.7954999999997 g/mol

分子质量是2540.0325 g/mol

分子质量是2171.6443 g/mol

分子质量是2191.6735999999996 g/mol

分子质量是4872.453500000002 g/mol

分子质量是1091.3435 g/mol

分子质量是2383.8468 g/mol

分子质量是2682.2243 g/mol

分子质量是2592.2161 g/mol

分子质量是2760.2964999999995 g/mol

分子质量是2696.2576999999997 g/mol

分子质量是3164.7239 g/mol

分子质量是2932.3923000000004 g/mol

分子质量是2589.9983000000007 g/mol

分子质量是1883.2978000000003 g/mol

分子质量是1939.4041000000002 g/mol

分子质量是6224.417800000003 g/mol

分子质量是3432.114599999999 g/mol

分子质量是3211.9924 g/mol

分子质量是2036.4180000000001 g/mol

分子质量是4276.265700000001 g/mol

分子质量是2546.9703999999997 g/mol

分子质量是1881.2601000000004 g/mol

分子质量是1478.7332999999999 g/mol

分子质量是3633.5111000000006 g/mol

分子质量是4627.391400000002 g/mol

分子质量是4196.890700000002 g/mol

分子质量是2864.1863 g/mol

分子质量是3529.034200000001 g/mol

分子质量是3225.850200000001 g/mol

分子质量是4047.683100000002 g/mol

分子质量是2287.6947999999998 g/mol

分子质量是3042.503100000001 g/mol

分子质量是3877.4207000000006 g/mol

分子质量是2036.4180000000001 g/mol

分子质量是2004.4407999999999 g/mol

分子质量是1600.9836000000003 g/mol

分子质量是1946.2905999999998 g/mol

分子质量是1959.3754999999996 g/mol

分子质量是2003.3850000000002 g/mol

分子质量是2016.4699 g/mol

分子质量是3083.5019 g/mol

分子质量是2408.7106 g/mol

分子质量是3411.0023 g/mol

分子质量是1610.0851 g/mol

分子质量是2273.8903 g/mol

分子质量是3123.749800000001 g/mol

分子质量是2660.1761000000006 g/mol

分子质量是2870.448900000001 g/mol

分子质量是2820.390300000001 g/mol

分子质量是2162.5862 g/mol

分子质量是2406.8752000000004 g/mol

分子质量是1607.0795 g/mol

分子质量是1636.2036 g/mol

分子质量是2118.8634000000006 g/mol

分子质量是1153.5438000000001 g/mol

分子质量是1153.5438000000001 g/mol

分子质量是2118.8634000000006 g/mol

分子质量是2390.9930000000004 g/mol

分子质量是1636.2036 g/mol

分子质量是1289.6086 g/mol

分子质量是1840.3007999999998 g/mol

分子质量是2074.5174 g/mol

分子质量是2703.2818 g/mol

分子质量是1445.753 g/mol

分子质量是1776.1362000000001 g/mol

分子质量是4032.7957000000006 g/mol

分子质量是4069.910500000002 g/mol

分子质量是4108.886600000002 g/mol

分子质量是4035.8943000000017 g/mol

分子质量是2399.7946 g/mol

分子质量是3556.2367000000013 g/mol

分子质量是3646.3592000000012 g/mol

分子质量是3124.7064000000005 g/mol

分子质量是3735.453900000001 g/mol

分子质量是3035.611700000001 g/mol

分子质量是3051.6541000000007 g/mol

分子质量是2891.5046000000007 g/mol

分子质量是2054.6504 g/mol

分子质量是3820.667800000001 g/mol

分子质量是1494.9462999999998 g/mol

分子质量是3420.370000000001 g/mol

分子质量是1764.2496 g/mol

分子质量是3971.870200000002 g/mol

分子质量是2899.5665000000013 g/mol

分子质量是1463.808 g/mol

分子质量是1744.2204 g/mol

分子质量是2811.5062000000003 g/mol

分子质量是2917.5849000000007 g/mol

分子质量是2164.6799000000005 g/mol

分子质量是3415.224600000001 g/mol

分子质量是2813.3545000000004 g/mol

分子质量是2025.4437000000003 g/mol

分子质量是2919.4249000000004 g/mol

分子质量是2316.0562000000004 g/mol

分子质量是2749.415 g/mol

分子质量是1668.0781000000002 g/mol

分子质量是1587.05 g/mol

分子质量是1632.0492 g/mol

分子质量是1674.1289 g/mol

分子质量是1544.9702999999997 g/mol

分子质量是1964.2925000000002 g/mol

分子质量是1910.1491000000003 g/mol

分子质量是1766.0237 g/mol

分子质量是1908.2657000000002 g/mol

分子质量是1854.1289000000004 g/mol

分子质量是1946.2687000000003 g/mol

分子质量是1878.2363000000003 g/mol

分子质量是2024.3409000000004 g/mol

分子质量是1955.2806000000003 g/mol

分子质量是1878.2363000000003 g/mol

分子质量是2633.362800000001 g/mol

分子质量是4076.110300000002 g/mol

分子质量是3076.8540000000003 g/mol

分子质量是4178.7349 g/mol

分子质量是4867.658899999999 g/mol

分子质量是4714.392600000001 g/mol

分子质量是5179.035600000001 g/mol

分子质量是4931.5767000000005 g/mol

分子质量是4786.498300000001 g/mol

分子质量是4997.676300000001 g/mol

分子质量是2085.5733000000005 g/mol

分子质量是2156.6943000000006 g/mol

分子质量是2254.8837000000003 g/mol

分子质量是2281.9521000000004 g/mol

分子质量是2323.0471000000002 g/mol

分子质量是2354.1042 g/mol

分子质量是2197.7893000000004 g/mol

分子质量是2239.7664 g/mol

分子质量是1344.5696000000003 g/mol

分子质量是1330.543 g/mol

分子质量是2945.5073 g/mol

分子质量是2472.9714 g/mol

分子质量是1460.7295000000001 g/mol

分子质量是1423.7076000000002 g/mol

分子质量是1460.7295000000001 g/mol

分子质量是2011.5363000000002 g/mol

分子质量是1970.4413 g/mol

分子质量是2612.2888000000003 g/mol

分子质量是2627.3035 g/mol

分子质量是2585.2237999999998 g/mol

分子质量是2543.1441 g/mol

分子质量是2585.2237999999998 g/mol

分子质量是2514.1459 g/mol

分子质量是2581.9633 g/mol

分子质量是1918.4096 g/mol

分子质量是1961.4377 g/mol

分子质量是1933.4243000000001 g/mol

分子质量是1989.5306000000005 g/mol

分子质量是2018.5719000000008 g/mol

分子质量是2060.5721000000003 g/mol

分子质量是1888.1451 g/mol

分子质量是3128.693399999999 g/mol

分子质量是3382.0421000000006 g/mol

分子质量是1724.0865 g/mol

分子质量是1395.7504 g/mol

分子质量是1471.8463 g/mol

分子质量是1452.8447999999999 g/mol

分子质量是1487.8456999999999 g/mol

分子质量是3715.4921000000004 g/mol

分子质量是3379.0597000000007 g/mol

分子质量是3715.4921000000004 g/mol

分子质量是3379.0597000000007 g/mol

分子质量是3975.818900000001 g/mol

分子质量是4640.297699999999 g/mol

分子质量是4088.738300000001 g/mol

分子质量是2005.6644000000001 g/mol

分子质量是1932.6121000000003 g/mol

分子质量是1764.3345 g/mol

分子质量是1676.2675 g/mol

分子质量是1449.9523 g/mol

分子质量是2230.8289999999993 g/mol

分子质量是1070.3327000000002 g/mol

分子质量是1397.7465 g/mol

分子质量是1392.7681999999998 g/mol

分子质量是1458.7879999999998 g/mol

分子质量是2847.4471000000003 g/mol

分子质量是1623.9774000000002 g/mol

分子质量是1567.9125 g/mol

分子质量是3164.7438 g/mol

分子质量是1884.3734999999997 g/mol

分子质量是1661.0802999999999 g/mol

分子质量是3175.860600000001 g/mol

分子质量是1686.007 g/mol

分子质量是3843.5618999999997 g/mol

分子质量是2043.6246 g/mol

分子质量是5200.617900000002 g/mol

分子质量是2739.2948000000006 g/mol

分子质量是2995.708699999999 g/mol

分子质量是2873.4777000000004 g/mol

分子质量是1518.8418000000001 g/mol

分子质量是1548.8678 g/mol

分子质量是4259.274700000001 g/mol

分子质量是4079.902000000001 g/mol

分子质量是4152.308900000001 g/mol

分子质量是2880.5181999999995 g/mol

分子质量是2650.0356000000006 g/mol

分子质量是2460.8680000000004 g/mol

分子质量是2417.9343 g/mol

分子质量是1512.8339999999998 g/mol

分子质量是2814.2451 g/mol

分子质量是3539.0914999999995 g/mol

分子质量是1030.1826999999998 g/mol

分子质量是2890.3495000000003 g/mol

分子质量是2322.9179 g/mol

分子质量是3042.503100000001 g/mol

分子质量是3877.4207000000006 g/mol

分子质量是3440.0488 g/mol

分子质量是3322.8579000000004 g/mol

分子质量是3397.9691 g/mol

分子质量是3443.0097000000005 g/mol

分子质量是4818.8717000000015 g/mol

分子质量是3436.0204000000003 g/mol

分子质量是3552.1816000000003 g/mol

分子质量是2693.1131 g/mol

分子质量是2430.933000000001 g/mol

分子质量是2670.2041 g/mol

分子质量是2307.7174999999997 g/mol

分子质量是2895.4805000000006 g/mol

分子质量是493.57489999999996 g/mol

分子质量是1478.99 g/mol

分子质量是1394.8306 g/mol

分子质量是1465.9515999999999 g/mol

分子质量是2733.2125000000015 g/mol

分子质量是2394.8099 g/mol

分子质量是2076.5073 g/mol

分子质量是4207.088100000002 g/mol

分子质量是5962.2844000000005 g/mol

分子质量是5931.271900000002 g/mol

分子质量是6250.6518000000015 g/mol

分子质量是5666.859100000001 g/mol

分子质量是5248.0307 g/mol

分子质量是6058.267500000001 g/mol

分子质量是5927.153899999998 g/mol

分子质量是4316.2435 g/mol

分子质量是6157.351500000002 g/mol

分子质量是5767.873500000003 g/mol

分子质量是6234.474 g/mol

分子质量是5030.0181 g/mol

分子质量是5402.409699999997 g/mol

分子质量是1303.5144 g/mol

分子质量是1344.5696000000003 g/mol

分子质量是2562.2301 g/mol

分子质量是1942.3914 g/mol

分子质量是2561.0826 g/mol

分子质量是2562.1122 g/mol

分子质量是3134.7178000000004 g/mol

分子质量是3169.7569000000003 g/mol

分子质量是3308.913800000001 g/mol

分子质量是3245.813400000001 g/mol

分子质量是2463.8351999999995 g/mol

分子质量是2519.1242000000007 g/mol

分子质量是2436.9342 g/mol

分子质量是2546.0252 g/mol

分子质量是2048.578 g/mol

分子质量是1898.3605000000002 g/mol

分子质量是2101.5047000000004 g/mol

分子质量是2396.7991 g/mol

分子质量是1983.4051 g/mol

分子质量是3018.6805000000004 g/mol

分子质量是1816.1189000000002 g/mol

分子质量是4191.983200000001 g/mol

分子质量是1905.3015000000005 g/mol

分子质量是2118.5419 g/mol

分子质量是2217.6763 g/mol

分子质量是2132.5685 g/mol

分子质量是2203.6497 g/mol

分子质量是2132.5685000000003 g/mol

分子质量是2153.6341 g/mol

分子质量是2217.6763 g/mol

分子质量是2155.607 g/mol

分子质量是2098.5523000000003 g/mol

分子质量是2090.4888000000005 g/mol

分子质量是2175.5966000000003 g/mol

分子质量是2189.6232000000005 g/mol

分子质量是2090.4888 g/mol

分子质量是1798.2677999999999 g/mol

分子质量是2372.0564000000004 g/mol

分子质量是3088.7339 g/mol

分子质量是2474.1135000000004 g/mol

分子质量是3805.5474000000013 g/mol

分子质量是3659.3169000000016 g/mol

分子质量是3747.382200000002 g/mol

分子质量是2269.6547999999993 g/mol

分子质量是1682.0828999999999 g/mol

分子质量是1756.1861999999999 g/mol

分子质量是3414.9194 g/mol

分子质量是4550.481 g/mol

分子质量是2346.7871000000005 g/mol

分子质量是3488.2175000000007 g/mol

分子质量是2516.0693000000006 g/mol

分子质量是1680.0557 g/mol

分子质量是1485.8083 g/mol

分子质量是2531.0835999999995 g/mol

分子质量是2435.9365 g/mol

分子质量是3080.6423000000013 g/mol

分子质量是2292.7363000000005 g/mol

分子质量是5524.4812999999995 g/mol

分子质量是6639.680500000001 g/mol

分子质量是8585.845999999994 g/mol

分子质量是5707.5615 g/mol

分子质量是2163.6356 g/mol

分子质量是1938.3481000000002 g/mol

分子质量是2304.7405 g/mol

分子质量是1742.1019 g/mol

分子质量是2148.5548 g/mol

分子质量是2020.4256 g/mol

分子质量是6927.833200000002 g/mol

分子质量是7374.3448000000035 g/mol

分子质量是2391.9301 g/mol

分子质量是2263.7578 g/mol

分子质量是3781.5191999999997 g/mol

分子质量是3455.0583999999994 g/mol

分子质量是3473.0750999999996 g/mol

分子质量是3023.6804 g/mol

分子质量是2850.5104999999994 g/mol

分子质量是2840.366899999999 g/mol

分子质量是3175.860600000001 g/mol

分子质量是3080.6423000000013 g/mol

分子质量是1256.5774000000001 g/mol

分子质量是955.1325999999999 g/mol

分子质量是2888.5206000000003 g/mol

分子质量是1838.0983 g/mol

分子质量是1399.7159999999997 g/mol

分子质量是2888.5206000000003 g/mol

分子质量是2402.8568 g/mol

分子质量是2778.0658 g/mol

分子质量是1465.6928 g/mol

分子质量是6517.2021 g/mol

分子质量是4086.8285000000005 g/mol

分子质量是14459.985199999992 g/mol

分子质量是1876.2455000000004 g/mol

分子质量是4393.026000000002 g/mol

分子质量是2939.649900000001 g/mol

分子质量是9391.690899999998 g/mol

分子质量是6149.100300000002 g/mol

分子质量是9107.174099999998 g/mol

分子质量是3382.0421000000006 g/mol

分子质量是16448.615099999995 g/mol

分子质量是3455.0583999999994 g/mol

分子质量是3473.0750999999996 g/mol

分子质量是3023.6804 g/mol

分子质量是2850.5104999999994 g/mol

分子质量是5805.776000000001 g/mol

分子质量是3080.6423000000013 g/mol

分子质量是2292.7363000000005 g/mol

分子质量是4897.516299999999 g/mol

分子质量是4751.367000000001 g/mol

分子质量是2326.6779000000006 g/mol

分子质量是2107.5371999999998 g/mol

分子质量是6517.2021 g/mol

分子质量是6500.267500000002 g/mol

分子质量是4086.8285000000005 g/mol

分子质量是2645.1132000000002 g/mol

分子质量是8585.845999999994 g/mol

分子质量是14459.985199999992 g/mol

分子质量是1876.2455000000004 g/mol

分子质量是1860.1533 g/mol

分子质量是2402.8568 g/mol

分子质量是2778.0658 g/mol

分子质量是4393.026000000002 g/mol

分子质量是2147.6047000000003 g/mol

分子质量是2146.6630000000005 g/mol

分子质量是3878.6095000000005 g/mol

分子质量是3073.7724000000007 g/mol

分子质量是2426.8983000000003 g/mol

分子质量是2902.5305000000003 g/mol

分子质量是2483.9927 g/mol

分子质量是2903.4424 g/mol

分子质量是2885.4256 g/mol

分子质量是3431.109300000001 g/mol

分子质量是7905.5250000000015 g/mol

分子质量是3160.7946 g/mol

分子质量是6577.6432 g/mol

分子质量是12040.89929999999 g/mol

分子质量是3316.9742000000006 g/mol

分子质量是3256.9222 g/mol

分子质量是3401.095600000001 g/mol

分子质量是3158.6929999999998 g/mol

分子质量是3299.8640000000005 g/mol

分子质量是5520.4395 g/mol

分子质量是4629.415600000001 g/mol

分子质量是7243.918400000002 g/mol

分子质量是9326.852299999997 g/mol

分子质量是7091.390499999998 g/mol

分子质量是19596.85059999998 g/mol

分子质量是1526.8191999999997 g/mol

分子质量是10609.992899999996 g/mol

分子质量是10623.018199999993 g/mol

分子质量是5563.376800000001 g/mol

分子质量是1923.2611000000002 g/mol

分子质量是3686.1345 g/mol

分子质量是5200.617900000002 g/mol

分子质量是11271.695899999993 g/mol

分子质量是3628.5394000000015 g/mol

分子质量是14071.121399999984 g/mol

分子质量是3800.7607000000016 g/mol

分子质量是4089.8783999999996 g/mol

分子质量是2102.5923 g/mol

分子质量是3138.8786 g/mol

分子质量是12006.67149999999 g/mol

分子质量是2230.8289999999993 g/mol

分子质量是5223.8524 g/mol

分子质量是2971.5772999999995 g/mol

分子质量是3339.8613999999993 g/mol

分子质量是2946.5780999999997 g/mol

分子质量是2921.433000000001 g/mol

分子质量是2902.3729000000003 g/mol

分子质量是3820.5054999999993 g/mol

分子质量是3814.5423999999994 g/mol

分子质量是1907.2693000000002 g/mol

分子质量是1808.2211 g/mol

分子质量是2594.0383 g/mol

分子质量是1838.2453000000003 g/mol

分子质量是2523.9401000000007 g/mol

分子质量是1754.0825000000002 g/mol

分子质量是3368.1118 g/mol

分子质量是1999.3134 g/mol

分子质量是3111.6564 g/mol

分子质量是3193.6474000000003 g/mol

分子质量是3984.661500000002 g/mol

分子质量是1923.3598999999997 g/mol

分子质量是4751.367000000001 g/mol

分子质量是3206.5649999999996 g/mol

分子质量是6890.929000000004 g/mol

分子质量是1087.2785000000001 g/mol

分子质量是1106.3249 g/mol

分子质量是935.1245 g/mol

分子质量是1078.3115 g/mol

分子质量是1063.2968 g/mol

分子质量是1097.313 g/mol

分子质量是1136.3491000000001 g/mol

分子质量是1113.3124 g/mol

分子质量是1051.2431000000001 g/mol

分子质量是1021.2171 g/mol

分子质量是1078.2684000000002 g/mol

分子质量是1788.0113000000001 g/mol

分子质量是2402.8568 g/mol

分子质量是2778.0658 g/mol

分子质量是3128.693399999999 g/mol

分子质量是1133.3834 g/mol

分子质量是9107.174099999998 g/mol

分子质量是3382.0421000000006 g/mol

分子质量是3455.0583999999994 g/mol

分子质量是3473.0750999999996 g/mol

分子质量是3023.6804 g/mol

分子质量是2850.5104999999994 g/mol

分子质量是2840.366899999999 g/mol

分子质量是950.1392 g/mol

分子质量是5805.776000000001 g/mol

分子质量是2263.7560999999996 g/mol

分子质量是4819.300000000001 g/mol

分子质量是4949.457899999999 g/mol

分子质量是4720.223199999999 g/mol

分子质量是4255.787699999999 g/mol

分子质量是2326.6779000000006 g/mol

分子质量是3762.4510999999984 g/mol

分子质量是2325.839 g/mol

分子质量是6500.267500000002 g/mol

分子质量是2531.0835999999995 g/mol

分子质量是4086.8285000000005 g/mol

分子质量是4012.7448000000013 g/mol

分子质量是4614.266900000001 g/mol

分子质量是1224.3700000000001 g/mol

分子质量是4203.037600000001 g/mol

分子质量是1876.2455000000004 g/mol

分子质量是12006.67149999999 g/mol

分子质量是1582.9237000000003 g/mol

分子质量是9107.174099999998 g/mol

分子质量是14459.985199999992 g/mol

分子质量是2435.9365 g/mol

分子质量是2163.6356 g/mol

分子质量是1938.3481000000002 g/mol

分子质量是2304.7405 g/mol

分子质量是2148.5548 g/mol

分子质量是2020.4256 g/mol

分子质量是4086.8285000000005 g/mol

分子质量是3490.0128 g/mol

分子质量是4393.026000000002 g/mol

分子质量是1556.8584999999998 g/mol

分子质量是1528.7621999999997 g/mol

分子质量是1985.2589000000003 g/mol

分子质量是1427.6999 g/mol

分子质量是1427.6999 g/mol

分子质量是1457.7241 g/mol

分子质量是1457.7241 g/mol

分子质量是1512.8058999999998 g/mol

分子质量是1514.7787999999998 g/mol

分子质量是1485.7374999999997 g/mol

分子质量是1514.7788 g/mol

分子质量是1457.7240999999997 g/mol

分子质量是1485.7374999999997 g/mol

分子质量是4243.874499999999 g/mol

分子质量是3933.651499999999 g/mol

分子质量是3979.6800999999996 g/mol

分子质量是3833.4015 g/mol

分子质量是1327.5276999999999 g/mol

分子质量是6579.1982000000025 g/mol

分子质量是2920.4295999999995 g/mol

分子质量是2892.4161999999997 g/mol

分子质量是2286.7234 g/mol

分子质量是1866.1662000000001 g/mol

分子质量是2711.1283 g/mol

分子质量是5416.224500000001 g/mol

分子质量是2794.2989000000007 g/mol

分子质量是2487.9 g/mol

分子质量是2955.5584999999996 g/mol

分子质量是2765.0994999999994 g/mol

分子质量是2854.3584 g/mol

分子质量是2759.2541 g/mol

分子质量是2259.7011 g/mol

分子质量是2859.3316999999993 g/mol

分子质量是2665.2688000000007 g/mol

分子质量是2851.225099999999 g/mol

分子质量是2356.8525999999997 g/mol

分子质量是2176.6111999999994 g/mol

分子质量是2504.975299999999 g/mol

分子质量是2749.1843 g/mol

分子质量是5200.617900000002 g/mol

分子质量是5572.307500000001 g/mol

分子质量是2609.9880000000007 g/mol

分子质量是4667.3228 g/mol

分子质量是2946.5780999999997 g/mol

分子质量是6620.5021000000015 g/mol

分子质量是3455.0583999999994 g/mol

分子质量是3473.0750999999996 g/mol

分子质量是3023.6804 g/mol

分子质量是2850.5104999999994 g/mol

分子质量是2840.366899999999 g/mol

分子质量是3455.0583999999994 g/mol

分子质量是3473.0750999999996 g/mol

分子质量是3023.6804 g/mol

分子质量是2850.5104999999994 g/mol

分子质量是2840.366899999999 g/mol

分子质量是4076.110300000002 g/mol

分子质量是3175.860600000001 g/mol

分子质量是3715.4921000000004 g/mol

分子质量是3379.0597000000007 g/mol

分子质量是5200.617900000002 g/mol

分子质量是3628.5394000000015 g/mol

分子质量是3800.7607000000016 g/mol

分子质量是4089.8783999999996 g/mol

分子质量是3984.7479000000003 g/mol

分子质量是3820.5054999999993 g/mol

分子质量是3814.5423999999994 g/mol

分子质量是2230.8289999999993 g/mol

分子质量是2971.5772999999995 g/mol

分子质量是3339.8613999999993 g/mol

分子质量是493.57489999999996 g/mol

分子质量是10147.670799999996 g/mol

分子质量是2924.5177000000003 g/mol

分子质量是5805.776000000001 g/mol

分子质量是6500.267500000002 g/mol

分子质量是2292.7363000000005 g/mol

分子质量是4061.654700000001 g/mol

分子质量是1868.2584000000002 g/mol

分子质量是2478.951 g/mol

分子质量是2921.433000000001 g/mol

分子质量是1376.6842000000001 g/mol

分子质量是2107.5371999999998 g/mol

分子质量是4897.516299999999 g/mol

分子质量是4751.367000000001 g/mol

分子质量是3628.5394000000015 g/mol

分子质量是2971.5772999999995 g/mol

分子质量是3339.8613999999993 g/mol

分子质量是2902.3729000000003 g/mol

分子质量是2435.9365 g/mol

分子质量是3080.6423000000013 g/mol

分子质量是2292.7363000000005 g/mol

分子质量是1969.4384 g/mol

分子质量是3781.5191999999997 g/mol

分子质量是13599.732099999976 g/mol

分子质量是5524.4812999999995 g/mol

分子质量是6639.680500000001 g/mol

分子质量是5304.167399999999 g/mol

分子质量是4078.642200000001 g/mol

分子质量是10225.749499999996 g/mol

分子质量是11052.563899999994 g/mol

分子质量是7286.282200000002 g/mol

分子质量是4734.5148 g/mol

分子质量是2163.6356 g/mol

分子质量是1938.3481000000002 g/mol

分子质量是2304.7405 g/mol

分子质量是1742.1019 g/mol

分子质量是2148.5548 g/mol

分子质量是1515.7866999999999 g/mol

分子质量是2020.4256 g/mol

分子质量是2888.5206000000003 g/mol

分子质量是1465.7392 g/mol

分子质量是1030.1826999999998 g/mol

分子质量是2890.3495000000003 g/mol

分子质量是4127.590500000001 g/mol

分子质量是3425.9059000000007 g/mol

分子质量是3437.9596000000006 g/mol

分子质量是5962.2844000000005 g/mol

分子质量是5931.271900000002 g/mol

分子质量是6058.267500000001 g/mol

分子质量是5927.153899999998 g/mol

分子质量是5767.873500000003 g/mol

分子质量是5402.409699999997 g/mol

分子质量是2252.5595 g/mol

分子质量是2888.5206000000003 g/mol

分子质量是2292.7363000000005 g/mol

分子质量是1237.4067 g/mol

分子质量是6110.287600000002 g/mol

分子质量是4388.9858 g/mol

分子质量是1465.7392 g/mol

分子质量是10305.368299999995 g/mol

分子质量是4311.0747 g/mol

分子质量是4273.9153000000015 g/mol

分子质量是3217.4599 g/mol

分子质量是3217.4599 g/mol

分子质量是6224.417800000003 g/mol

分子质量是3217.4599 g/mol

分子质量是3975.818900000001 g/mol

分子质量是4640.297699999999 g/mol

分子质量是4088.738300000001 g/mol

分子质量是1427.9106 g/mol

分子质量是1370.8161999999998 g/mol

分子质量是1370.8161999999998 g/mol

分子质量是1370.8162 g/mol

分子质量是1370.8161999999998 g/mol

分子质量是1370.8162 g/mol

分子质量是1370.8161999999998 g/mol

分子质量是1370.8162 g/mol

分子质量是1370.8162 g/mol

分子质量是1370.8162 g/mol

分子质量是1396.8535 g/mol

分子质量是1396.8535 g/mol

分子质量是1396.8535 g/mol

分子质量是1370.8162 g/mol

分子质量是1525.0258 g/mol

分子质量是1396.8535 g/mol

分子质量是1396.8535 g/mol

分子质量是1396.8535 g/mol

分子质量是1396.8535 g/mol

分子质量是1396.8535 g/mol

分子质量是1396.8535 g/mol

分子质量是1370.8162 g/mol

分子质量是1396.8535 g/mol

分子质量是5134.982399999999 g/mol

分子质量是1507.9451 g/mol

分子质量是2833.2497 g/mol

分子质量是1565.0394999999999 g/mol

分子质量是1565.0394999999999 g/mol

分子质量是1622.1338999999998 g/mol

分子质量是2144.594 g/mol

分子质量是4801.5163999999995 g/mol

分子质量是4127.590500000001 g/mol

分子质量是7089.307100000001 g/mol

分子质量是2227.5587 g/mol

分子质量是2252.5595 g/mol

分子质量是4251.8994 g/mol

分子质量是4235.900000000001 g/mol

分子质量是3382.0421000000006 g/mol

分子质量是2316.0562000000004 g/mol

分子质量是1819.2786000000006 g/mol

分子质量是2888.5206000000003 g/mol

分子质量是6119.118600000001 g/mol

分子质量是5898.018099999999 g/mol

分子质量是1810.2568999999999 g/mol

分子质量是1907.2693000000002 g/mol

分子质量是2292.7363000000005 g/mol

分子质量是1969.4384 g/mol

分子质量是1654.9898999999998 g/mol

分子质量是3317.9618 g/mol

分子质量是1910.4141 g/mol

分子质量是1406.7948000000001 g/mol

分子质量是3935.3671999999997 g/mol

分子质量是3425.9059000000007 g/mol

分子质量是1661.0802999999999 g/mol

分子质量是1614.004 g/mol

分子质量是1735.0742999999998 g/mol

分子质量是4086.8285000000005 g/mol

分子质量是4061.654700000001 g/mol

分子质量是2424.7990999999997 g/mol

分子质量是3437.9596000000006 g/mol

分子质量是2551.9206 g/mol

分子质量是1406.8413 g/mol

分子质量是1444.8477 g/mol

分子质量是3591.2358999999997 g/mol

分子质量是4136.761200000001 g/mol

分子质量是1774.1599000000003 g/mol

分子质量是1808.2211 g/mol

分子质量是2594.0383 g/mol

分子质量是1838.2453000000003 g/mol

分子质量是2523.9401000000007 g/mol

分子质量是1773.1289 g/mol

分子质量是1754.0825000000002 g/mol

分子质量是1044.2255 g/mol

分子质量是5637.564700000002 g/mol

分子质量是2223.7818 g/mol

分子质量是3590.524300000002 g/mol

分子质量是4330.734500000002 g/mol

分子质量是2592.9740999999995 g/mol

分子质量是4393.026000000002 g/mol

分子质量是3731.2398999999996 g/mol

分子质量是12006.67149999999 g/mol

分子质量是8654.762699999997 g/mol

分子质量是3617.3099 g/mol

分子质量是2010.4236999999998 g/mol

分子质量是2442.0238000000004 g/mol

分子质量是1426.5757999999998 g/mol


In [9]:
# 1. 显示所有列 (不省略中间的列)
pd.set_option('display.max_columns', None)

# 2. 显示所有行 (注意：如果数据有几万行，请谨慎使用，或改用 .head(100))
pd.set_option('display.max_rows', None)

# 3. 显示单元格内所有字符 (防止抗菌肽序列 Sequence 被截断)
pd.set_option('display.max_colwidth', None)

# 4. 确保输出宽度不换行
pd.set_option('display.width', 1000)
print(long_df["Raw_Species"].value_counts())

Raw_Species
MIC (E. coli)                             1212
MIC (S. aureus)                           1105
MIC (E. coli ATCC 25922)                   637
MIC (C. albicans)                          560
MIC (P. aeruginosa)                        513
MIC (B. subtilis)                          406
MIC (S. aureus ATCC 25923)                 401
MIC (S. epidermidis)                       299
MIC (P. aeruginosa ATCC 27853)             291
MIC (M. luteus)                            241
MIC (K. pneumoniae)                        238
MIC (A. baumannii)                         181
MIC (E. faecalis)                          179
MIC (E. faecium)                           156
MIC (S. aureus ATCC 29213)                 152
MIC (B. cereus)                            143
MIC (E. coli ATCC25922)                    142
MIC (L. monocytogenes)                     137
MIC (S. typhimurium)                       128
MIC (P. aeruginosa PAO1)                   128
MIC (S. enterica)                          127
MIC (A. baumannii ATCC 19606)              104
MIC (K. pneumoniae ATCC 700603)             98
MIC (S. aureus ATCC25923)                   97
MIC (S. aureus ATCC 6538)                   97
MIC (E. faecalis ATCC 29212)                97
MIC (S. aureus USA300)                      94
MIC (B. subtilis ATCC 6633)                 92
MIC (E. faecalis ATCC29212)                 83
MIC (C. albicans ATCC2002)                  82
MIC (S. epidermidis ATCC 12228)             81
MIC (B. pyocyaneus)                         80
MIC (P. aeruginosa ATCC27853)               75
MIC (E. cloacae)                            74
MIC (B. megaterium)                         71
MIC (K. pneumoniae ATCC 13883)              70
MIC (S. cerevisiae)                         67
MIC (S. typhimurium ATCC 14028)             64
MIC (E. coli DH5)                           60
MIC (E. coli ATCC 8739)                     60
MIC (N. asteroides)                         55
MIC (A. baumannii ATCC19606)                54
MIC (P. aeruginosa ATCC 9027)               51
MIC (L. lactis)                             50
MIC (E. coli BW25113)                       49
MIC (E. coli BL21)                          48
MIC (S. aureus ATCC6538)                    48
MIC (C. neoformans)                         47
MIC (S. aureus ATCC2592)                    47
MIC (P. faecalis X29)                       47
MIC (F. oxysporum)                          45
MIC (K. pneumoniae ATCC700603)              45
MIC (S. uberis)                             45
MIC (S. enteritidis)                        42
MIC (C. albicans ATCC 10231)                41
MIC (C. glabrata)                           41
MIC (B. cinerea)                            40
MIC (S. pyogenes)                           40
MIC (B. dysenteriae)                        39
MIC (C. tropicalis)                         37
MIC (S. aureus ATCC29213)                   37
MIC (L. innocua)                            36
MIC (C. parapsilosis ATCC 22019)            33
MIC (K. pneumoniae ATCC 10031)              33
MIC (E. faecium ATCC 700221)                32
MIC (E. coli K12)                           32
MIC (L. monocytogenes ATCC 19115)           31
MIC (P. mirabilis)                          30
MIC (B. cereus ATCC 10876)                  29
MIC (E. coli JM109)                         28
MIC (E. coli KCTC 1682)                     28
MIC (C. parapsilosis ATCC22019)             28
MIC (E. coli ATCC 11775)                    28
MIC (A. niger)                              28
MIC (A. hydrophila)                         27
MIC (A. fumigatus)                          27
MIC (S. typhimurium KCTC 1926)              27
MIC (S. aureus ATCC 43300)                  27
MIC (R. rhodochrous X15)                    27
MIC (B. subtilis ATCC 23857)                26
MIC (C. albicans ATCC 90028)                26
MIC (B. licheniformis X39)                  26
MIC (S. aureus AB94004)                     25
MIC (S. flexneri)                           25
MIC (S. carnosus)                           25
MIC (P. aeruginosa CGMCC 1)                 24
MIC (A. viridans)                           24
MIC (S. aureus ATCC 12600)                  24
MIC (B. subtilis KCTC 3068)                 24
MIC (V. alginolyticus)                      23
MIC (B. subtilis IFO 3513)                  23
MIC (C. glutamicum ATCC 13032)              23
MIC (K. pneumoniae ATCC 43816)              23
MIC (S. agalactiae)                         23
MIC (P. aeruginosa KCTC 1637)               23
MIC (V. parahaemolyticus ISP 72)            23
MIC (S. aureus IFO 12732)                   23
MIC (P. syringae)                           22
MIC (P. putida)                             22
MIC (A. salmonicida)                        22
MIC (V. anguillarum)                        22
MIC (E. coli D31)                           22
MIC (S. aureus ATCC43300)                   22
MIC (E. faecalis NCTC 12697)                22
MIC (M. luteus ATCC 10240)                  22
MIC (S. epidermidis KCTC 1917)              21
MIC (V. parahaemolyticus)                   21
MIC (S. maltophilia)                        21
MIC (P. vulgaris)                           21
MIC (E. coli IFO 12734)                     20
MIC (S. enterica ATCC 14028)                20
MIC (E. aerogenes)                          20
MIC (E. coli ML35)                          20
MIC (S. mutans)                             20
MIC (E. faecium ATCC 19434)                 20
MIC (E. cloacae ATCC13047)                  20
MIC (B. pyocyaneus CMCCB1010)               20
MIC (E. coli UB1005)                        20
MIC (V. vulnificus)                         19
MIC (S. aureus RN4220)                      19
MIC (K. pneumonia)                          19
MIC (S. epidermidis AB208187)               19
MIC (N. crassa)                             19
MIC (F. culmorum)                           18
MIC (E. coli CGSC4908)                      18
MIC (P. aeruginosa Z61)                     18
MIC (V. parahaemolyticus ATCC17802)         18
MIC (S. aureus KCTC 1621)                   18
MIC (S. sciuri P254)                        18
MIC (S. pyogenes ATCC 19615)                18
MIC (S. aureus ATCC 29212)                  18
MIC (E. coli ATCC 11219)                    17
MIC (C. albicans ATCC90028)                 17
MIC (P. aeruginosa ATCC 13388)              17
MIC (C. neoformans H99)                     17
MIC (P. aeruginosa PA01)                    17
MIC (S. lactis)                             17
MIC (F. graminearum)                        17
MIC (P. aeruginosa H103)                    17
MIC (S. aureus CGMCC 1)                     17
MIC (L. monocytogenes ATCC 15313)           16
MIC (A. pullulans)                          16
MIC (B. subtilis BNCC109047)                16
MIC (S. choleraesuis CVCC503)               16
MIC (A. sobria)                             16
MIC (E. coli MG1655)                        16
MIC (S. dysenteriae)                        16
MIC (B. anthracis)                          16
MIC (K. oxytoca)                            16
MIC (A. baumannii BAA 747)                  15
MIC (A. baumannii ATCC 17978)               15
MIC (P. digitatum)                          15
MIC (S. pneumoniae ATCC 49619)              15
MIC (E. coli O157)                          15
MIC (A. nidulans)                           15
MIC (E. coli MDR 1057)                      15
MIC (P. multocida)                          15
MIC (S. saprophyticus)                      15
MIC (C. krusei ATCC 6258)                   15
MIC (P. aeruginosa PA14)                    14
MIC (K. pneumoniae IS 59)                   14
MIC (C. albicans SC5314)                    14
MIC (S. iniae)                              14
MIC (E. coli AB94012)                       14
MIC (E. coli DC2)                           14
MIC (B. subtilis ATCC 6051)                 14
MIC (C. glutamicum)                         13
MIC (S. epidermidis C621)                   13
MIC (P. aeruginosa K799)                    13
MIC (P. fluorescens)                        13
MIC (V. harveyi)                            13
MIC (E. cloacae ATCC 13047)                 13
MIC (P. pastoris)                           13
MIC (A. brassicola)                         13
MIC (E. coli ATCC 35218)                    13
MIC (C. albicans C627)                      13
MIC (E. tarda)                              13
MIC (B. subtilis ATCC6633)                  13
MIC (S. dysentariae ATCC 9752)              13
MIC (S. epidermidis CGMCC 1)                13
MIC (K. pneumoniae CGMCC 1)                 12
MIC (E. cloacae CGMCC 1)                    12
MIC (E. coil CGMCC 1)                       12
MIC (X. campestris)                         12
MIC (V. cholerae)                           12
MIC (S. marcescens ATCC 8100)               12
MIC (C. albicans MDM8)                      12
MIC (N. haematococca)                       12
MIC (P. aeruginos)                          12
MIC (C. parapsilosis)                       12
MIC (F. oxysporum CECT2866)                 12
MIC (L. anguillarum)                        12
MIC (P. italicum)                           12
MIC (C. acnes)                              12
MIC (V. splendidus)                         11
MIC (L. garvieae)                           11
MIC (V. parahaemolyticus ATCC 17802)        11
MIC (T. beigelii)                           11
MIC (C. albicans ATCC 14053)                11
MIC (E. coli D22)                           11
MIC (S. aureus ATCC 2592)                   11
MIC (A. globiformis)                        11
MIC (X. axonopodis)                         11
MIC (E. coli E423)                          11
MIC (S. pullorum)                           11
MIC (E. faecalis PCM 2673)                  11
MIC (P. expansum)                           11
MIC (B. dendrobatidis)                      11
MIC (E. coli ATCC 25726)                    11
MIC (B. subtilis CECT498)                   11
MIC (S. cerevisiae FY1679)                  11
MIC (M. luteus ATCC 9341)                   11
MIC (A. flavus)                             11
MIC (S. aureus SH1000)                      10
MIC (K. pneumoniae DSM 30104)               10
MIC (S. xylosus)                            10
MIC (S. sonnei)                             10
MIC (S. rubidaea X01)                       10
MIC (E. coli IS117)                         10
MIC (E. coli IS37)                          10
MIC (E. coli AIC221)                        10
MIC (S. pneumoniae)                         10
MIC (T. rubrum)                             10
MIC (C. perfringens)                        10
MIC (S. aureus NCTC 6538)                   10
MIC (S. typhimurium ATCC14028)              10
MIC (S. aureus NCTC 10788)                  10
MIC (T. viride)                              9
MIC (M. luteus A270)                         9
MIC (P. aeruginosa ATCC 15692)               9
MIC (C. difficile ATCC 43602)                9
MIC (A. veronii)                             9
MIC (A. niger ATCC 16404)                    9
MIC (E. coli ATCC8739)                       9
MIC (E. coli IS218)                          9
MIC (Y. enterocolitica)                      9
MIC (S. pullorum C79)                        9
MIC (B. subtilis AB91021)                    9
MIC (B. thuringiensis)                       9
MIC (S. aureus IS37)                         9
MIC (S. aureus IS10)                         9
MIC (S. aureus ATCC 9144)                    9
MIC (S. aureus ATCC 33591)                   9
MIC (P. aeruginosa E411)                     9
MIC (P. aeruginosa IS350)                    9
MIC (P. aeruginosa DSM 1117)                 9
MIC (S. typhi)                               9
MIC (C. tropicalis ATCC 750)                 9
MIC (P. aeruginosa AB93066)                  9
MIC (C. difficile)                           9
MIC (K. pneumoniae MKP103)                   9
MIC (S. epidermidis LY8)                     9
MIC (C. albicans ATCC 2002)                  9
MIC (C. freundii)                            9
MIC (M. luteus AB2010179)                    8
MIC (M. luteus AB93113)                      8
MIC (M. smegmatis)                           8
MIC (K. pneumoniae LMG20218)                 8
MIC (S. maltophilia ATCC 13637)              8
MIC (S. enteritidis CVCC3377)                8
MIC (S. haemolyticus)                        8
MIC (S. epidermidis ATCC12228)               8
MIC (B. subtilis KCTC 2217)                  8
MIC (P. acnes)                               8
MIC (S. enterica AB 2010185)                 8
MIC (S. aureus NCTC 8325)                    8
MIC (S. aureus KCTC1621)                     8
MIC (P. aeruginosa IS 350)                   8
MIC (F. solani)                              8
MIC (B. cereus ATCC 11778)                   8
MIC (E. coli CCT 1371)                       8
MIC (B. megatherium)                         8
MIC (S. aureus AB 94004)                     8
MIC (B. pumilus)                             8
MIC (S. agalactiae ATCC 13813)               8
MIC (C. albicans ATCC 20032)                 8
MIC (S. alactolyticus)                       8
MIC (E. faecalis MF 06036)                   8
MIC (E. faecium A634)                        8
MIC (B. cereus ATCC 14579)                   8
MIC (S. simulans)                            8
MIC (E. coli CVCC195)                        8
MIC (B. subtilis CMCC 63501)                 8
MIC (S. marcescens)                          8
MIC (B. subtilis BR151)                      8
MIC (E. faecium NCTC 12201)                  8
MIC (E. faecium ATCC29212)                   8
MIC (H. influenzae)                          8
MIC (V. brasiliensis)                        8
MIC (C. jejuni)                              8
MIC (A. baumannii B28)                       7
MIC (A. baumanii)                            7
MIC (L. rhamnosus)                           7
MIC (S. sanguinis)                           7
MIC (C. krusei)                              7
MIC (C. krusei IFM56881)                     7
MIC (C. glabrata ATCC 90030)                 7
MIC (E. coli DH1)                            7
MIC (S. faecalis)                            7
MIC (C. neoformans B3501)                    7
MIC (C. jeikeium)                            7
MIC (R. solani)                              7
MIC (E. agglomerans)                         7
MIC (E. amylovora)                           7
MIC (S. aureus IS 10)                        7
MIC (K. pneumonia ATCC 700603)               7
MIC (K. pneumonia ATCC13883)                 7
MIC (E. coli D21)                            7
MIC (L. fleischmannii)                       7
MIC (P. acidolactici)                        7
MIC (K. pneumoniae ATCC 43)                  7
MIC (S. epidermidis RP62)                    7
MIC (B. cereus ATCC14579)                    7
MIC (S. faecalis ATCC 29212)                 7
MIC (S. intermedius)                         7
MIC (S. choleraesuis)                        7
MIC (N. asteroids)                           7
MIC (S. pullorum CVCC1789)                   7
MIC (S. pseudintermedius)                    7
MIC (E. faecalis JCM 5803)                   7
MIC (E. faecalis LMG16216)                   7
MIC (C. albicans ATCC 90029)                 7
MIC (S. aureus SG511)                        7
MIC (C. perfringens ATCC 13124)              7
MIC (E. faecium LMG16003)                    7
MIC (E. coli DSM 787)                        7
MIC (A. terreus)                             7
MIC (A. tumefaciens)                         7
MIC (S. suis CVCC3309)                       6
MIC (E. coli HB 101)                         6
MIC (B. coagulans JCM 2257)                  6
MIC (P. avium C48)                           6
MIC (A. pisi)                                6
MIC (C. parasitica)                          6
MIC (S. dysentariae)                         6
MIC (S. choleraesuis C78)                    6
MIC (A. johnsonii)                           6
MIC (L. lactis MG1363)                       6
MIC (S. aureus MTCC 9542)                    6
MIC (S. aureus LMG10147)                     6
MIC (K. pneumoniae ATCC13883)                6
MIC (K. pneumoniae CMCC46117)                6
MIC (B. thuringiensis AB92037)               6
MIC (S. mould)                               6
MIC (S. mutans UA159)                        6
MIC (S. typhimurium SL1344)                  6
MIC (S. hemolyticus)                         6
MIC (H. pylori)                              6
MIC (P. putida NCIM 2102)                    6
MIC (S. lutea)                               6
MIC (E. coli BW 25113)                       6
MIC (S. aureus ATCC12600)                    6
MIC (B. subtilis CICC24434)                  6
MIC (M. maritypicum CIP 105733)              6
MIC (M. tuberculosis)                        6
MIC (S. aureus DSM 11729)                    6
MIC (V. fluvialis)                           6
MIC (S. warneri)                             6
MIC (P. aeruginosa LMG6395)                  6
MIC (K. pneumonia ATCC 10031)                6
MIC (E. cloacae CI 4172)                     6
MIC (S. aurerus)                             6
MIC (E. coli W 160)                          6
MIC (E. coli IS 37)                          6
MIC (L. innocua ATCC 33090)                  6
MIC (E. faecium CMCC1)                       6
MIC (E. faecium IS 1299)                     6
MIC (S. pyogenes ATCC19615)                  6
MIC (E. coli B21)                            6
MIC (C. koseri)                              6
MIC (C. michiganensis)                       6
MIC (S. enteriditis)                         6
MIC (P. aeruginosa H085180216)               6
MIC (P. aeruginosa CMCC10104)                6
MIC (C. albicans NCYC 1467)                  6
MIC (A. baunmannii)                          6
MIC (A. baumannii KCTC 2508)                 6
MIC (A. baumannii ATCC17978)                 6
MIC (A. calcoaceticus)                       6
MIC (S. pneumoniae CVCC1)                    6
MIC (S. aureus IS 37)                        6
MIC (Y. pseudotuberculosis)                  6
MIC (Y. pestis EV76)                         6
MIC (V. parahamelytics CCRC10806)            6
MIC (A. baumannii DSM 30008)                 6
MIC (A. baumanii CI 2675)                    6
MIC (A. niger IP218)                         5
MIC (L. monocytogenes LMG10470)              5
MIC (M. luteus ATCC 49732)                   5
MIC (L. sakei)                               5
MIC (S. aureus PTCC1431)                     5
MIC (C. neoformans IP960)                    5
MIC (E. coli IS 218)                         5
MIC (E. coli SBS 363)                        5
MIC (L. ivanovii)                            5
MIC (D. formicogenerans)                     5
MIC (L. maculans)                            5
MIC (M. luteus ATCC 15307)                   5
MIC (C. albicans IP884)                      5
MIC (A. caviae IP67)                         5
MIC (E. coli IP76)                           5
MIC (E. faecium LMG11423)                    5
MIC (P. aeruginosa MR3007)                   5
MIC (P. aeruginosa ATCC 105663)              5
MIC (P. aeruginosa DSM 50071)                5
MIC (B. circulans JCM 2504)                  5
MIC (E. coli ATCC 9723)                      5
MIC (K. pneumonia ATCC 43816)                5
MIC (B. pyocyaneum ATCC 27853)               5
MIC (B. dysenterium)                         5
MIC (B. pyocyaneus CMCCB10104)               5
MIC (E. coli CGMCC 1)                        5
MIC (N. brasiliensis IP118079)               5
MIC (B. subtilis CMCC63501)                  5
MIC (S. suis CVCC606)                        5
MIC (S. cerevisiae IP118079)                 5
MIC (S. cerevisiae ATCC 2601)                5
MIC (S. homonis ATCC 27844)                  5
MIC (S. musiva)                              5
MIC (P. aeruginosa ATCC 25853)               5
MIC (E. faecalis IP103214)                   5
MIC (S. aureus CCRC12652)                    5
MIC (C. utrechtense)                         5
MIC (S. marcescens ATCC8100)                 5
MIC (C. difficile R20291)                    5

In [28]:
import json
import time
with open("../AMP_COMMON_SPECIES.json", "r") as f:
    AMP_COMMON_SPECIES = json.load(f)

from Bio import Entrez
Entrez.email = "luyeqing21@mail.ustc.edu.cn"
def get_tax_id(species_name: str) -> str:
    term = f"{species_name}[Scientific Name]"
    handle = Entrez.esearch(db="taxonomy", term=term)
    record = Entrez.read(handle)

    if not record["IdList"]:
        print("No taxonomy ID found for the given species.")
        return None
    tax_id = record["IdList"][0]
    return str(tax_id)

SPECIES_TAX_ID = {}
tax_in_none = []
for species_name in AMP_COMMON_SPECIES.values():
    SPECIES_TAX_ID[species_name] = get_tax_id(species_name)
    time.sleep(0.5)  # 为了避免过于频繁的请求，添加延时
    if SPECIES_TAX_ID[species_name] is None:
        tax_in_none.append(species_name)

print(f"以下物种未找到对应的Taxonomy ID：{tax_in_none}")

with open("../SPECIES_TAX_ID.json", "w") as f:
    json.dump(SPECIES_TAX_ID, f, indent=4)

No taxonomy ID found for the given species.
No taxonomy ID found for the given species.
No taxonomy ID found for the given species.
No taxonomy ID found for the given species.
No taxonomy ID found for the given species.
No taxonomy ID found for the given species.
No taxonomy ID found for the given species.
以下物种未找到对应的Taxonomy ID：['Propionibacterium acnes', 'Candida glabrata', 'Lactobacillus salivarius', 'Listeria iavanovii', 'Candida krusei', 'Salmonella typhimurium', 'Salmonella enteritidis']

In [18]:
# 统一一下物种名称第一个是species，第二个是genes， 跟json文件对应起来

from rapidfuzz.distance import Levenshtein

with open("../POSSIBLE_GENES.json", "r") as f:
    POSSIBLE_GENES = json.load(f)

with open("../POSSIBLE_SPECIES.json", "r") as f:
    POSSIBLE_SPECIES = json.load(f)

with open("../SPECIES_TAX_ID.json", "r") as f:
    SPECIES_TAX_ID = json.load(f)

with open("../AMP_COMMON_SPECIES.json", "r") as f:
    AMP_COMMON_SPECIES = json.load(f)

def correct_species_with_distance(
    species_initial,
    genus_raw, 
    max_distance=2
):
    """
    raw_name: e.g. 'S. aureu'
    max_distance: 建议 1 或 2（非常重要）
    """

    best_match = None
    best_distance = None
    genus_list = POSSIBLE_GENES[species_initial]
    for genus in genus_list:
        dist = Levenshtein.distance(genus_raw, genus)

        if best_distance is None or dist < best_distance:
            best_distance = dist
            best_match = genus

    if best_distance is not None and best_distance <= max_distance:
        corrected = f"{species_initial}. {best_match}"
        return corrected, best_distance, "corrected"
    raw_name = f"{species_initial}. {genus_raw}"
    return raw_name, best_distance, "unchanged"

def NCBI_search(species:str, genus:str)->Tuple[str,str]:
    term = f"{species} {genus}[Scientific Name]"
    handle = Entrez.esearch(db="taxonomy", term=term)
    record = Entrez.read(handle)

    if not record["IdList"]:
        print(f"No taxonomy ID found for the given species:{species} {genus}.")
        return None, None
    tax_id = record["IdList"][0]
    summary = Entrez.efetch(db="taxonomy", id=tax_id, retmode="xml")
    data = Entrez.read(summary)

    sci_name = data[0]["ScientificName"]
    return tax_id, sci_name

def abbr2sci_name(abbr_name: str) -> Tuple[str, str]:
    abbr_name_set = AMP_COMMON_SPECIES.keys()
    # 缩写可以直接在本地找到
    if abbr_name in abbr_name_set:
        sci_name = AMP_COMMON_SPECIES[abbr_name]
        tax_id = SPECIES_TAX_ID[sci_name]  
        return tax_id, sci_name
    # 如果不在预定义的缩写中，先检查是否种名拼写有问题
    names = abbr_name.split()
    initial = names[0][0]
    genus = names[1]
    corrected_species, distance, status = correct_species_with_distance(initial, genus)
    if status == "corrected":
        sci_name = AMP_COMMON_SPECIES[corrected_species]
        tax_id = SPECIES_TAX_ID[sci_name]  
        return tax_id, sci_name
    
    # 最后尝试在POSSIBLE_SPECIES.json里面使用首字母组合，使用NCBI API搜索
    candidate_species = POSSIBLE_SPECIES[initial]
    for sp in candidate_species:
        tax_id, sci_name = NCBI_search(sp, genus)
        if tax_id:
            return tax_id, sci_name
        time.sleep(0.5)  # 为了避免过于频繁的请求，添加延时

    return None, None  # 如果不匹配，返回原始名称

In [21]:
name_df = pd.DataFrame()
# 1. 使用 .copy() 明确创建一个独立的对象，解决 SettingWithCopyWarning
name_df = long_df["Raw_Species"].drop_duplicates().to_frame(name="raw")
name_df = name_df.iloc[9:10].copy() 

# 2. 使用 apply 结合 pd.Series 批量更新，解决结果为 NaN 的问题
# 注意：result_type='expand' 可以将返回的元组拆分到三列
print("正在提取物种信息...")
name_df[["Tax_ID", "Target_Species", "Strain"]] = name_df["raw"].apply(
    lambda x: pd.Series(extract_bacterium_and_strain(x))
)

print(name_df)

正在提取物种信息...
                          raw Tax_ID           Target_Species Strain
57559  MIC (A. baumannii AB1)    470  Acinetobacter baumannii    AB1

In [22]:
long_df.head(3)

       APD_ID       Sequence  Length                                  Activity                          Raw_Species   MIC_Value  MIC_Value(ug/ml)
3090  AP03328  TLKIIVKVVKYLV      13  Anti-Gram+ & Gram-, Anti-MRSA, Hemolytic  MIC (A. acidoterrestris ATCC 49025)  0.5 ug/ml)          0.500000
8503  AP02677       FWQKMSFA       8                        Anti-Gram+ & Gram-             MIC (A. acidoterrestris)     16  uM)         16.707608
9152  AP03328  TLKIIVKVVKYLV      13  Anti-Gram+ & Gram-, Anti-MRSA, Hemolytic             MIC (A. acidoterrestris)  0.5 ug/ml)          0.500000

In [23]:
long_df = long_df.merge(name_df, left_on="Raw_Species",right_on="raw", how="left")
long_df.head(3)

    APD_ID       Sequence  Length                                  Activity                          Raw_Species   MIC_Value  MIC_Value(ug/ml)  raw Tax_ID Target_Species Strain
0  AP03328  TLKIIVKVVKYLV      13  Anti-Gram+ & Gram-, Anti-MRSA, Hemolytic  MIC (A. acidoterrestris ATCC 49025)  0.5 ug/ml)          0.500000  NaN    NaN            NaN    NaN
1  AP02677       FWQKMSFA       8                        Anti-Gram+ & Gram-             MIC (A. acidoterrestris)     16  uM)         16.707608  NaN    NaN            NaN    NaN
2  AP03328  TLKIIVKVVKYLV      13  Anti-Gram+ & Gram-, Anti-MRSA, Hemolytic             MIC (A. acidoterrestris)  0.5 ug/ml)          0.500000  NaN    NaN            NaN    NaN

In [68]:
long_df["Target_Species"] = long_df["Target_Species_y"]

In [69]:
long_df = long_df[["APD_ID", "Sequence", "Length", "Activity", "MIC_Value(ug/ml)", "Tax_ID", "Target_Species", "Strain"]]
long_df.to_csv("APD6_final_processed.csv", index=False)

In [13]:
# 把raw_species列中的变成 target_species，strain_ID 
from typing import Tuple
def extract_bacterium_and_strain(raw_text:str)->Tuple[str,str,str]:
    # 返回(tax_id : 562, species : Staphylococcus aureus, strain : ATCC 25922)
    match = re.search(r'MIC\s*\((.*)\)', str(raw_text))
    if not match:
        return None, None, None
    full_content = match.group(1).strip() # 例如 "A. baumanii CI 2675"
    parts = full_content.split()
    if len(parts) > 2:
        species_part = " ".join(parts[:2]) # "A. baumanii"
        strain_part = " ".join(parts[2:])   # "CI 2675"
    else:
        species_part = full_content
        strain_part = None

    tax_id, species = abbr2sci_name(species_part)
    if not tax_id:
        print(f"无法为物种名称找到Taxonomy ID: {species_part}\n")
        
    return tax_id, species, strain_part

In [50]:
print(extract_bacterium_and_strain("MIC (A. baumannii AB1)"))

('470', 'Acinetobacter baumannii', 'AB1')

In [ ]:
df = pd.read_csv("final_APD6_MIC_processed.csv", dtype={'Tax_ID':str})
df["Raw_Species"] = df["Raw_Species"].apply(lambda x: x[x.find('(')+1:x.find(')')] )

df['Raw_Species'].value_counts()

Raw_Species
E. coli                   1212
S. aureus                 1105
E. coli ATCC 25922         637
C. albicans                560
P. aeruginosa              513
                          ...
A. ochraceus CGMCC 3         1
A. parasiticus               1
A. sydowii EF239             1
A. sydowii MEF 239           1
S. typhimurium CGMCC 1       1
Name: count, Length: 1163, dtype: int64

In [6]:
df.to_csv("final_APD6_MIC_processed.csv")